### ISSUE TITLE
Can you please share how django-webpack-loader is installed? Is it just pip install django-webpack-loader or its's with 1) npm install @angular-devkit/custom-webpack --save  2) npm install @angular-builders/custom-webpack --save  3)npm install webpack-bundle-tracker --save

### ISSUE THREAD

**Issue by codernn** [nvishnya/django-channels-angular-template#8]

**Comment by liashchevska** [comment]
django-webpack-loader uses the output generated by webpack-bundle-tracker. So to use it you need to:
- _pip install django-webpack-loader_
- _npm install webpack-bundle-tracker --save_
- _npm install @angular-builders/custom-webpack --save_ (custom-webpack is used to modify angular configuration, in webpack.config.js webpack-bundle-tracker is set up and then in angular.json we point out to webpack.config.js file using custom-webpack)
